server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.132.129:1111 # 配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
