server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: 192.168.132.129:1111
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用会自动从8719开始一次+1扫描，直至找到被占用的端口。
        port: 8719
          # 添加Nacos数据源配置
      datasource:
        ds1: # 数据源1
          nacos:
            server-addr: 192.168.132.129:1111
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 流控规则
management:
  endpoints:
    web:
      exposure:
        include: "*"
